#################################
#             Shadows           #
#################################

backend = "glx"
vsync=true;
detect-client-opacity=true;
use-damage=true;
#blur:
#{
#method = "gaussian";
#size = 10; 
#deviation = 15;
#};
#
opacity-rule = [
  "85:class_g = 'Com.github.xournalpp.xournalpp'"
];
